version: "3.4"
services:
  molgenis:
    image: crs4/molgenis-app:10.2.0
    user: 0:0
    environment:
      - environment=production
      - molgenis.home=/home/molgenis
      - opencpu.uri.host=opencpu
      - elasticsearch.hosts=elasticsearch:9200
      - db_uri=jdbc:postgresql://postgres/molgenis
      - db_user=molgenis
      - db_password=molgenis
      - admin.password=admin
      - MINIO_BUCKET_NAME=molgenis
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=molgenis
      - MINIO_SECRET_KEY=molgenis
      - MOLGENIS_MAX_FILE_MB=150
      - "CATALINA_OPTS=-Xmx1g"
      - audit.log.path=/home/molgenis/audit/audit.log
    ports:
      - "8080:8080"
    volumes:
      - app-data:/home/molgenis
      - audit-log:/home/molgenis/audit
    depends_on:
      - postgres
      - elasticsearch
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 20s
      retries: 5
      start_period: 20s
      timeout: 10s
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=molgenis
      - POSTGRES_PASSWORD=molgenis
      - POSTGRES_DB=molgenis
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data
    command: -c 'shared_buffers=256MB' -c 'max_locks_per_transaction=1024'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - cluster.name=molgenis
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    expose:
      - 9200
  minio:
    image: minio/minio:RELEASE.2019-03-20T22-38-47Z
    volumes:
      - minio-data:/data
    expose:
      - 9000
    environment:
      MINIO_ACCESS_KEY: molgenis
      MINIO_SECRET_KEY: molgenis
    command: server /data
  beacon:
    image: crs4/beacon-2:latest
    hostname: beacon
    environment:
      - SERVER_NAME=beacon
      - PORT=5050
      - SSL_ENABLED=false
    volumes:
      - ../conf/config.molgenis.yml:/beacon/config.yml
    ports:
      - "5050:5050"
    depends_on:
      molgenis:
        condition: service_healthy
volumes:
  audit-log:
  db-data:
  app-data:
  es-data:
  minio-data:
    driver: local
