version: '3.1'

services:
  beacon:
    image: crs4/beacon-2:latest
    hostname: beacon
    environment:
      - SERVER_NAME=beacon
      - PORT=5050
      - SSL_ENABLED=false
    volumes:
      - ../conf/config.fhir.yml:/beacon/config.yml
      - ./logger.yml:/beacon/beacon/logger.yml
    ports:
      - "5050:5050"

  store:
    image: "samply/blaze:0.21"
    environment:
      BASE_URL: "http://localhost:8080"
      JAVA_TOOL_OPTIONS: "-Xmx4g"
    volumes:
      - "store-db-data:/app/data"
    restart: "unless-stopped"
    ports:
      - "8080"

volumes:
  store-db-data:
